### ISSUE TITLE
Update swagger-parser version

### ISSUE THREAD

**Issue by marcusnaweb** [dzdrazil/swagger-mock-api#13]
Hi, the current version of swagger-parser referred in package.json can't resolve $ref's like "../../2-Middleware/GTW-Hotels/Hotels.yml#/definitions/Error".

Updating swagger-parser to v3.4.1 (and changing the .parse calls to .dereference calls) solved it to me. Should I make a PR?

Thanks.

**Comment by dzdrazil** [comment]
~This should be updated in the next release tonight.~

Scratch that, it's just been released.  1.6.0 has this change plus your merge request.  Thanks!
