### ISSUE TITLE
Possible solution for circular-refs

### ISSUE THREAD

**Issue by zzswang** [dzdrazil/swagger-mock-api#6]
Hi dzdrazil,

I found there is an issue of circular-refs, which is explained in (swagger-parser) [https://www.npmjs.com/package/swagger-parser#circular-refs]

A quick exmaple:

``` yaml
...
Definitions:
    Document:
        origin_doc: 
            $ref: '#/definitions/Document'
...
```

origin_doc is actually a document instance, so now we have a circular reference error.

It is explained in swagger-parser, which is said currently not a good way to support it, but we can ignore such error at least.

So I did some code change in /dist, I want to discuss it with you first.

in dist/index.js

``` javascript
_swaggerParser2['default'].parse(config.swaggerFile, function (err, api) {
      if (err) throw err;

      if (config.ignorePaths) {
        api.paths = (0, _PrunePaths2['default'])(api.paths, config.ignorePaths);
      } else if (config.mockPaths) {
        api.paths = (0, _PrunePaths2['default'])(api.paths, config.mockPaths, true);
      }
```

change to

``` javascript
    _swaggerParser2['default'].parse(config.swaggerFile, function (err, api) {
      if (err && !(err instanceof ReferenceError)){
       throw err;
     }

      if (config.ignorePaths) {
        api.paths = (0, _PrunePaths2['default'])(api.paths, config.ignorePaths);
      } else if (config.mockPaths) {
        api.paths = (0, _PrunePaths2['default'])(api.paths, config.mockPaths, true);
      }
```

in dist/MockData.js

``` javascript
  for (var k in schema) {
    if (schema[k].type === 'array') {
      ret[k] = generateArray(schema[k]);
      continue;
    }

    ret[k] = swaggerToChance(schema[k]);
  }
```

change to 

``` javascript
  for (var k in schema) {
    if (k == '$ref'){
      continue;
    }

    if (schema[k].type === 'array') {
      ret[k] = generateArray(schema[k]);
      continue;
    }
    ret[k] = swaggerToChance(schema[k]);
  }
```

What do you think about the change?
And do you have time to fix it? I'm not quite familiar with the source code under /src, but I can have a try.

**Comment by dzdrazil** [comment]
This one will be a little more tricky- I'd like to attempt to allow recursive / cyclic references, but require the user to specify a minimum and maximum depth.

So, your example above would be:

``` yaml
...
Definitions:
    Document:
        origin_doc: 
            $ref: '#/definitions/Document'
            x-min-depth: 0
            x-min-depth: 2
...
```

The expected behavior should be that a document may contain an origin_doc property that is not null, but there can be no more than a total of 3

```
document
  -> origin_doc: document
    -> origin_doc: document
```

That way, more control is left to the end user.

If you're interested in understanding the code in src a little better, it's all ES6 syntax; you can learn more about it at https://babeljs.io/docs/learn-es2015/ Many of the features will be natively available in node and browsers eventually, although I'mm using the babel transpiler to use them now :)

**Comment by zzswang** [comment]
Great, It would be much more flexible.

But did swagger-parser support to parse circular-refs? It seems only support to ignore it.

**Comment by zzswang** [comment]
I'll take some time to learn ES6, it is really helpful.

**Comment by dzdrazil** [comment]
I don't have a perfect solution for this yet, but I've got an idea that I think is workable. I haven't forgotten!

**Comment by zzswang** [comment]
Great~ It would be a major improvement :)

**Comment by bushuyev** [comment]
hi dzdrazil, any chance to have it fixed?

**Comment by lkiarest** [comment]
mark
